info:
  namespace: iasurvival
items:
  vyderlight_sword:
    enabled: true
    display_name: display-name-vyderlight_sword
    permission: iasurvival.special.vyderlight_sword
    resource:
      material: DIAMOND_SWORD
      generate: true
      textures:
        - item/swords/vyderlight_sword