info:
  namespace: nudon
items:
  penchan:
    enabled: true
    display_name: "ペンちゃん"
    resource:
      material: COOKED_CHICKEN
      generate: true
      textures:
        - fish/penchan
    events:
      eat:
        feed:
          amount: 4
          saturation: 0.4
