info:
  namespace: nudon
categories:
  ryouri:
    enabled: true
    skip_if_already: false
    icon: nudon:raamen
    name: 料理
    items:
      - nudon:kakigoori
      - nudon:karaage
      - nudon:pafe
      - nudon:raamen
      - nudon:sabaicon
      - nudon:tamanegi
      - nudon:saboten_wagiri
      - nudon:tosikosisoba
  syokuzai:
    enabled: true
    skip_if_already: false
    icon: iasurvival:tomato
    name: 食材
    items:
      - nudon:gohan
      - nudon:daizu

  fish:
    enabled: true
    skip_if_already: false
    icon: nudon:ahiruchan
    name: さかな
    items:
      - nudon:ahiruchan
      - nudon:penchan
  hat:
    name: 帽子
    icon: nudon:sakanaatama
    items:
      - nudon:sakanaatama
  misc:
    enabled: true
    skip_if_already: false
    icon: nudon:akatan
    name: そのほか
    items:
      - nudon:ichimanen
      - nudon:akatan
  seed:
    enabled: true
    skip_if_already: false
    icon: nudon:daizu_seeds
    name: 種や苗
    items:
      - nudon:daizu_seeds
