info:
  namespace: nudon
recipes:
  crafting_table:
    gohan:
      enabled: true
      shapeless: true
      ingredients:
        A: WHEAT
        B: TORCH
      result:
        item: nudon:gohan
        amount: 1


# cooking:
#   karaage:
#     machines:
#       - FURNACE
#       - SMOKER
#     ingredient:
#       item: COOKED_CHICKEN
#     result:
#       item: nudon:karaage
#       amount: 1
#   gohan:
#     machines:
#       - FURNACE
#       - SMOKER
#     ingredient:
#       item: WHEAT
#     result:
#       item: nudon:gohan
#       amount: 1
