info:
  namespace: iasurvival
categories:
  food:
    enabled: true
    skip_if_already: false
    icon: nudon:raamen
    name: たべもの
    items:
      - iasurvival:banana
      - iasurvival:tomato
      - iasurvival:french_fries
      - iasurvival:chips
      - iasurvival:sliced_cheese
      - iasurvival:pizza

