info:
  namespace: iasurvival
categories:
  food:
    enabled: true
    skip_if_already: false
    items:
      - iasurvival:banana
      - iasurvival:tomato
      - iasurvival:french_fries
      - iasurvival:chips


