info:
  namespace: iasurvival
recipes:
  crafting_table:
    french_fries:
      pattern:
        - XPX
        - XPX
        - XPX
      ingredients:
        P: BAKED_POTATO
      result:
        item: iasurvival:french_fries
        amount: 3
    chips:
      pattern:
        - XXX
        - PPP
        - XXX
      ingredients:
        P: BAKED_POTATO
      result:
        item: iasurvival:chips
        amount: 3
