info:
  namespace: iasurvival
recipes:
  crafting_table:
    french_fries:
      pattern:
        - PXX
        - PXX
        - PXX
      pattern2:
        - XPX
        - XPX
        - XPX
      pattern3:
        - XXP
        - XXP
        - XXP
      ingredients:
        P: BAKED_POTATO
      result:
        item: iasurvival:french_fries
        amount: 3
    chips:
      pattern:
        - PPP
        - XXX
        - XXX
      pattern2:
        - XXX
        - PPP
        - XXX
      pattern3:
        - XXX
        - XXX
        - PPP
      ingredients:
        P: BAKED_POTATO
      result:
        item: iasurvival:chips
        amount: 3
    sliced_cheese:
      shapeless: true
      enabled: true
      ingredients:
        A: MILK_BUCKET
      result:
        item: sliced_cheese
        amount: 4
    pizza:
      pattern:
        - CCC
        - TTT
        - PPP
      ingredients:
        P: BREAD
        T: tomato
        C: sliced_cheese
      result:
        item: pizza
        amount: 8

