info:
  namespace: iasurvival
items:
  dark_amethyst:
    enabled: true
    display_name: display-name-dark_amethyst
    permission: iasurvival.items.dark_amethyst
    resource:
      material: IRON_INGOT
      generate: true
      textures:
        - item/ores/dark_amethyst
