info:
  namespace: iasurvival
items:
  dark_amethyst_prism:
    enabled: true
    display_name: display-name-dark_amethyst_prism
    permission: iasurvival.items.dark_amethyst_prism
    resource:
      material: IRON_INGOT
      generate: true
      textures:
        - item/ores/dark_amethyst_prism
