info:
  namespace: iasurvival
items:
  chips:
    enabled: true
    display_name: ポテチ
    resource:
      material: COOKED_PORKCHOP
      generate: true
      textures:
        - food/chips
    events:
      eat:
        feed:
          amount: 6
          saturation: 6
