info:
  namespace: iasurvival
items:
  drink_glass:
    enabled: true
    display_name: display-name-drink_glass
    permission: iasurvival.items.drink_glass
    resource:
      material: STICK
      generate: true
      textures:
        - item/thirst/drink_glass
