info:
  namespace: iasurvival
items:
  hot_chocolate:
    enabled: true
    display_name: display-name-hot_chocolate
    permission: iasurvival.items.hot_chocolate
    resource:
      material: POTION
      generate: true
      textures:
        - item/thirst/hot_chocolate
    specific_properties:
      potion:
        type: WATER
        color: WHITE
    item_flags:
      - HIDE_POTION_EFFECTS
    events:
      drink:
        increment_player_stat:
          name: thirst
          amount: 5
