info:
  namespace: iadeco
items:
  simple_chair:
    enabled: true
    display_name: display-name-simple_chair
    permission: iadeco.chairs.simple_chair
    lore:
      - lore-chair
    resource:
      material: PAPER
      generate: false
      model_path: simple_chair
    behaviours:
      furniture:
        small: true
      furniture_sit:
        sit_height: 0.5
