info:
  namespace: iafestivities
items:
  santa_hat:
    enabled: true
    display_name: display-name-santa_hat
    permission: iafestivities.christmas.santa_hat
    resource:
      material: FEATHER
      generate: false
      model_path: christmas/santa_hat
    behaviours:
      hat: true
