info:
  namespace: silyouta
categories:
  ryouri:
    enabled: true
    skip_if_already: false
    icon: nudon:raamen
    name: 料理
    items:
      - silyouta:onigiri
      - silyouta:onigiri_syake
      - silyouta:onigiri_syake_jyou
      - silyouta:onigiri_syake_tokujyou
  syokuzai:
    enabled: true
    skip_if_already: false
    icon: iasurvival:tomato
    name: 食材
    items:
      - silyouta:ikura
      - silyouta:nori
      - silyouta:sio
