info:
  namespace: iasurvival
loots:
  blocks:
    grass:
      enabled: true
      type: SHORT_GRASS
      items:
        item_1:
          item: iasurvival:tomato_seeds
          min_amount: 1
          max_amount: 2
          chance: 5

