info:
  namespace: iasurvival
items:
  french_fries:
    enabled: true
    display_name: ポテト
    resource:
      material: COOKED_PORKCHOP
      generate: true
      textures:
        - food/french_fries
    events:
      eat:
        feed:
          amount: 8
          saturation: 2
