info:
  namespace: iasurvival
items:
  sliced_cheese:
    enabled: true
    display_name: チーズ
    resource:
      material: COOKED_PORKCHOP
      generate: true
      textures:
        - food/sliced_cheese
    events:
      eat:
        feed:
          amount: 2
          saturation: 0.2
