info:
  namespace: iadeco
items:
  glass_table:
    enabled: true
    display_name: display-name-glass_table
    permission: iadeco.decorations.glass_table
    lore:
      - lore-decorative-item
    resource:
      material: PAPER
      generate: false
      model_path: glass_table
    behaviours:
      furniture:
        small: true
        solid: true
