info:
  namespace: iasurvival
items:
  bronze_axe:
    enabled: true
    display_name: display-name-bronze_axe
    permission: iasurvival.items.bronze_axe
    resource:
      material: DIAMOND_AXE
      generate: true
      textures:
        - item/tools/bronze_axe
