info:
  namespace: iasurvival
items:
  bronze_hoe:
    enabled: true
    display_name: display-name-bronze_hoe
    permission: iasurvival.items.bronze_hoe
    resource:
      material: DIAMOND_HOE
      generate: true
      textures:
        - item/tools/bronze_hoe
