info:
  namespace: iasurvival
items:
  dark_amethyst_axe:
    enabled: true
    display_name: display-name-dark_amethyst_axe
    permission: iasurvival.items.dark_amethyst_axe
    resource:
      material: DIAMOND_AXE
      generate: true
      textures:
        - item/tools/dark_amethyst_axe
