info:
  namespace: silyouta

items:
  onigiri_syake_jyou:
    enabled: true
    display_name: "鮭おにぎり(上)"
    resource:
      material: PAPER
      generate: true
      textures:
        - ryouri/onigiri_syake_jyou
    nbt: '{components:{consumable:{consume_seconds:2},food:{nutrition:16,saturation:16}}}'
