info:
  namespace: silyouta

items:
  onigiri:
    enabled: true
    display_name: "おにぎり"
    resource:
      material: PAPER
      generate: true
      textures:
        - ryouri/onigiri
    nbt: '{components:{consumable:{consume_seconds:2},food:{nutrition:8,saturation:8}}}'
