info:
  namespace: silyouta

items:
  onigiri_syake:
    enabled: true
    display_name: "鮭おにぎり"
    resource:
      material: PAPER
      generate: true
      textures:
        - ryouri/onigiri_syake
    nbt: '{components:{consumable:{consume_seconds:2},food:{nutrition:12,saturation:12}}}'

