info:
  namespace: silyouta

items:
  onigiri_syake_tokujyou:
    enabled: true
    display_name: "鮭おにぎり(特上)"
    resource:
      material: PAPER
      generate: true
      textures:
        - ryouri/onigiri_syake_tokujyou
    nbt: '{components:{consumable:{consume_seconds:2},food:{nutrition:20,saturation:30}}}'
