info:
  namespace: silyouta

items:
  onigiri_syake:
    enabled: true
    display_name: "鮭おにぎり"
    resource:
      material: COOKED_BEEF
      generate: true
      textures:
        - ryouri/onigiri_syake
    events:
      eat:
        feed:
          amount: 12
          saturation: 12
