info:
  namespace: iaalchemy
items:
  energy_orb:
    enabled: true
    display_name: display-name-energy_orb
    permission: iaalchemy.items.energy.energy_orb
    lore:
      - lore-1-energy_orb
    resource:
      material: STICK
      generate: true
      textures:
        - item/energy_orb
  small_energy_capsule:
    enabled: true
    display_name: display-name-small_energy_capsule
    permission: iaalchemy.items.energy.small_energy_capsule
    lore:
      - lore-1-small_energy_capsule
    resource:
      material: STICK
      generate: true
      textures:
        - item/small_energy_capsule
  energy_capsule:
    enabled: true
    display_name: display-name-energy_capsule
    permission: iaalchemy.items.energy.energy_capsule
    lore:
      - lore-1-energy_capsule
      - lore-2-energy_capsule
    resource:
      material: STICK
      generate: true
      textures:
        - item/energy_capsule
