name: deploy to remote

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Install SSH key
            uses: shimataro/ssh-key-action@v2
            with:
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              known_hosts: ${{ secrets.KNOWN_HOSTS }}
              config: |
                Host server
                  HostName ${{ secrets.SSH_HOST }}
                  User ${{ secrets.SSH_USER }}
                  IdentityFile ~/.ssh/id_rsa
          - name: rsync over SSH
            run: rsync -acvz --delete -n --include-from=./include_list --exclude='*' ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/debian/ossan/plugins/ItemsAdder/
