name: deploy to remote

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up SSH
              uses: webfactory/ssh-agent@v0.5.3
              with:
                ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}


            - name: Run SSH command
              env:
                SSH_USER: ${{ secrets.SSH_USER }}
                SSH_HOST: ${{ secrets.SSH_HOST }}
              run: |
                ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST 'bash -s' <<'EOF'
                  ./daunrodo.sh
                  EOF
